CREATE TABLE IF NOT EXISTS `student_record` (`id` BIGINT NOT NULL AUTO_INCREMENT, `import_version` BIGINT NOT NULL DEFAULT 1, `import_task_id` VARCHAR(64) NULL, `student_no` VARCHAR(32) NOT NULL, `name` VARCHAR(64) NOT NULL, `age` INT NULL, `gender` VARCHAR(16) NULL, `class_name` VARCHAR(64) NULL, `email` VARCHAR(128) NULL, `birthday` VARCHAR(32) NULL, PRIMARY KEY (`id`), UNIQUE KEY `uk_student_record_version_student_no` (`import_version`, `student_no`), KEY `idx_student_record_version_id` (`import_version`, `id`), KEY `idx_student_record_import_task_id` (`import_task_id`)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `student_import_version_control` (`id` BIGINT NOT NULL, `current_version` BIGINT NOT NULL, `created_at` DATETIME NOT NULL, `updated_at` DATETIME NOT NULL, PRIMARY KEY (`id`)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

INSERT IGNORE INTO `student_import_version_control` (`id`, `current_version`, `created_at`, `updated_at`) VALUES (1, 1, NOW(), NOW());

CREATE TABLE IF NOT EXISTS `student_import_stage` (`id` BIGINT NOT NULL AUTO_INCREMENT, `import_task_id` VARCHAR(64) NOT NULL, `row_no` INT NOT NULL, `student_no` VARCHAR(256) NULL, `name` VARCHAR(256) NULL, `age` INT NULL, `gender` VARCHAR(64) NULL, `class_name` VARCHAR(256) NULL, `email` VARCHAR(512) NULL, `birthday` VARCHAR(128) NULL, `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP, PRIMARY KEY (`id`), KEY `idx_student_import_stage_task_row` (`import_task_id`, `row_no`), KEY `idx_student_import_stage_task_student_no` (`import_task_id`, `student_no`)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `student_report_run` (`id` BIGINT NOT NULL AUTO_INCREMENT, `run_id` VARCHAR(64) NOT NULL, `owner_id` VARCHAR(64) NOT NULL, `run_control_code` VARCHAR(64) NOT NULL, `run_name` VARCHAR(128) NOT NULL, `student_no` VARCHAR(32) NULL, `name_keyword` VARCHAR(64) NULL, `class_name` VARCHAR(64) NULL, `gender` VARCHAR(16) NULL, `min_age` INT NULL, `max_age` INT NULL, `status` VARCHAR(32) NOT NULL, `deleted` BIGINT NOT NULL DEFAULT 0, `created_at` DATETIME NOT NULL, `updated_at` DATETIME NOT NULL, PRIMARY KEY (`id`), UNIQUE KEY `uk_student_report_run_run_id` (`run_id`), UNIQUE KEY `uk_student_report_run_owner_code` (`owner_id`, `run_control_code`, `deleted`), KEY `idx_student_report_run_owner_created_at` (`owner_id`, `created_at`), KEY `idx_student_report_run_owner_status_created_at` (`owner_id`, `status`, `created_at`)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `file_record` (`id` BIGINT NOT NULL AUTO_INCREMENT, `file_id` VARCHAR(64) NOT NULL, `owner_id` VARCHAR(64) NOT NULL, `original_name` VARCHAR(255) NOT NULL, `object_key` VARCHAR(512) NOT NULL, `bucket_name` VARCHAR(128) NOT NULL, `content_type` VARCHAR(128) NULL, `file_size` BIGINT NOT NULL, `file_md5` CHAR(32) NOT NULL, `file_ext` VARCHAR(32) NULL, `storage_type` VARCHAR(32) NOT NULL, `status` VARCHAR(32) NOT NULL, `created_at` DATETIME NOT NULL, `updated_at` DATETIME NOT NULL, PRIMARY KEY (`id`), UNIQUE KEY `uk_file_record_file_id` (`file_id`), KEY `idx_file_record_owner_md5_size` (`owner_id`, `file_md5`, `file_size`), KEY `idx_file_record_status_created_at` (`status`, `created_at`)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `file_upload_task` (`id` BIGINT NOT NULL AUTO_INCREMENT, `upload_id` VARCHAR(64) NOT NULL, `file_id` VARCHAR(64) NOT NULL, `owner_id` VARCHAR(64) NOT NULL, `upload_type` VARCHAR(32) NOT NULL, `original_name` VARCHAR(255) NOT NULL, `object_key` VARCHAR(512) NOT NULL, `part_object_prefix` VARCHAR(512) NULL, `bucket_name` VARCHAR(128) NOT NULL, `content_type` VARCHAR(128) NULL, `file_size` BIGINT NOT NULL, `file_md5` CHAR(32) NOT NULL, `file_ext` VARCHAR(32) NULL, `status` VARCHAR(32) NOT NULL, `part_size` BIGINT NULL, `part_count` INT NULL, `created_at` DATETIME NOT NULL, `updated_at` DATETIME NOT NULL, `completed_at` DATETIME NULL, PRIMARY KEY (`id`), UNIQUE KEY `uk_file_upload_task_upload_id` (`upload_id`), KEY `idx_file_upload_task_owner_status_created_at` (`owner_id`, `status`, `created_at`), KEY `idx_file_upload_task_status_created_at` (`status`, `created_at`)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `async_task_record` (`id` BIGINT NOT NULL AUTO_INCREMENT, `task_id` VARCHAR(64) NOT NULL, `owner_id` VARCHAR(64) NOT NULL, `task_type` VARCHAR(32) NOT NULL, `task_name` VARCHAR(128) NOT NULL, `business_key` VARCHAR(128) NULL, `status` VARCHAR(32) NOT NULL, `progress_percent` INT NOT NULL, `total_count` BIGINT NOT NULL, `completed_count` BIGINT NOT NULL, `retry_count` INT NOT NULL, `max_retry_count` INT NOT NULL, `request_payload` TEXT NULL, `result_payload` TEXT NULL, `error_message` VARCHAR(1024) NULL, `failure_type` VARCHAR(32) NULL, `retryable` TINYINT(1) NULL, `failure_suggestion` VARCHAR(512) NULL, `worker_id` VARCHAR(128) NULL, `last_heartbeat_at` DATETIME NULL, `created_at` DATETIME NOT NULL, `updated_at` DATETIME NOT NULL, `started_at` DATETIME NULL, `finished_at` DATETIME NULL, `expire_at` DATETIME NOT NULL, PRIMARY KEY (`id`), UNIQUE KEY `uk_async_task_record_task_id` (`task_id`), KEY `idx_async_task_record_owner_created_at` (`owner_id`, `created_at`), KEY `idx_async_task_record_owner_business_key_created_at` (`owner_id`, `business_key`, `created_at`), KEY `idx_async_task_record_owner_status_created_at` (`owner_id`, `status`, `created_at`), KEY `idx_async_task_record_type_status_created_at` (`task_type`, `status`, `created_at`), KEY `idx_async_task_record_status_heartbeat` (`status`, `last_heartbeat_at`), KEY `idx_async_task_record_expire_at` (`expire_at`)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
