CREATE DATABASE IF NOT EXISTS `demo` CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `demo`.`student_record` (`id` BIGINT NOT NULL AUTO_INCREMENT, `student_no` VARCHAR(32) NOT NULL, `name` VARCHAR(64) NOT NULL, `age` INT NULL, `gender` VARCHAR(16) NULL, `class_name` VARCHAR(64) NULL, `email` VARCHAR(128) NULL, `birthday` VARCHAR(32) NULL, PRIMARY KEY (`id`)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
